

services:
  app: 
    build: .
    entrypoint: .docker/entrypoint.sh  
    container_name: apivendas-app
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app  
    depends_on: 
       - db
       - redis

  db:
    image: mysql:8.0
    container_name: apivendas-db
    restart: always
    tty: true
    ports: 
      - "3306:3306"
    volumes:
       - .docker/dbdata:/var/lib/mysql
    environment:
       - MYSQL_ROOT_PASSWORD=ari2002
       - MYSQL_DATABASE=apivendas

  redis:
    image: 'bitnami/redis:latest'
    container_name: apivendas-redis     
    environment:
       - ALLOW_EMPTY_PASSWORD=yes   
    ports:
      - "6379:6379"             